### ISSUE TITLE
Motor calculations

### ISSUE THREAD

**Issue by janabover** [Integrated-Project-2-2023-UVic-UCC/follow-me#4]
Calculations of the motors to know the type of the motors to buy

**Comment by EloiGarciaGisbert** [comment]
Motor Calculation

Since the chosen wheels had a radius of R=35 mm approximately, we can calculate the angular velocity (𝜔) at which the motor shaft should rotate.

v = w * R

Then we need to calculate the rpm of the wheels, the minimum and maximum to know the specifications of the motors:


In order to know the motor torque, we need to take in consideration the weight of the robot, the contact points touching the ground and  the friction of the surface. 


Then we can calculate the total torque needed in order to start moving the robot from standstill in each wheel. 


So each motor needs to have at least a torque of [0.105Nm · 4wheels / 2driven] = 0.210Nm.

From there now we can calculate the power which each wheel would need, although as there will be only 2 driven ones this total power will be distributed in those two.

So each motor needs to have at least a power of [1.5W · 4wheels / 2driven] = 3W.
